# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'costo_columna.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
import math
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog, QApplication
from PyQt5.QtWidgets import QWidget,QPushButton
import mss 
from datetime import datetime


class Ui_Costos(object):
    def setupUi(self, Costos):
        Costos.setObjectName("Costos")
        Costos.setWindowModality(QtCore.Qt.NonModal)
        Costos.setEnabled(True)
        Costos.resize(1216, 865)
        Costos.setSizeGripEnabled(False)
        Costos.setModal(False)
        self.label = QtWidgets.QLabel(Costos)
        self.label.setGeometry(QtCore.QRect(30, 190, 681, 611))
        self.label.setStyleSheet("border-image: url(:/imagenes/Imagenes/Captura.PNG);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Costos)
        self.label_2.setGeometry(QtCore.QRect(730, 550, 221, 251))
        self.label_2.setSizeIncrement(QtCore.QSize(1, 1))
        self.label_2.setBaseSize(QtCore.QSize(1, 0))
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("border-image: url(:/imagenes/Imagenes/f38b86e2df861bce1c56f8abb337d1a7.jpg);\n"
"border-color: rgb(0, 0, 0);")
        self.label_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.label_2.setLineWidth(23)
        self.label_2.setMidLineWidth(16)
        self.label_2.setText("")
        self.label_2.setScaledContents(True)
        self.label_2.setWordWrap(True)
        self.label_2.setOpenExternalLinks(True)
        self.label_2.setObjectName("label_2")
        self.btn_calcular = QtWidgets.QPushButton(Costos)
        self.btn_calcular.setGeometry(QtCore.QRect(960, 640, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_calcular.setFont(font)
        self.btn_calcular.setStyleSheet("background-color: rgb(73, 255, 70);")
        self.btn_calcular.setObjectName("btn_calcular")
        self.label_3 = QtWidgets.QLabel(Costos)
        self.label_3.setGeometry(QtCore.QRect(30, 70, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Costos)
        self.label_4.setGeometry(QtCore.QRect(350, 430, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Costos)
        self.label_5.setGeometry(QtCore.QRect(310, 470, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Costos)
        self.label_6.setGeometry(QtCore.QRect(380, 520, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Costos)
        self.label_7.setGeometry(QtCore.QRect(30, 220, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Costos)
        self.label_8.setGeometry(QtCore.QRect(30, 260, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Costos)
        self.label_9.setGeometry(QtCore.QRect(380, 200, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Costos)
        self.label_10.setGeometry(QtCore.QRect(400, 660, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Costos)
        self.label_11.setGeometry(QtCore.QRect(520, 200, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Costos)
        self.label_12.setGeometry(QtCore.QRect(30, 110, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Costos)
        self.label_13.setGeometry(QtCore.QRect(520, 610, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Costos)
        self.label_14.setGeometry(QtCore.QRect(380, 20, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Costos)
        self.label_15.setGeometry(QtCore.QRect(380, 70, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Costos)
        self.label_16.setGeometry(QtCore.QRect(380, 110, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Costos)
        self.label_17.setGeometry(QtCore.QRect(320, 240, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Costos)
        self.label_18.setGeometry(QtCore.QRect(290, 650, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(Costos)
        self.label_19.setGeometry(QtCore.QRect(330, 320, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(Costos)
        self.label_20.setGeometry(QtCore.QRect(270, 280, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_22 = QtWidgets.QLabel(Costos)
        self.label_22.setGeometry(QtCore.QRect(580, 290, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(Costos)
        self.label_23.setGeometry(QtCore.QRect(470, 750, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(Costos)
        self.label_24.setGeometry(QtCore.QRect(30, 10, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(Costos)
        self.label_25.setGeometry(QtCore.QRect(760, 20, 431, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("background-color: rgb(73, 255, 70);")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(Costos)
        self.label_26.setGeometry(QtCore.QRect(780, 80, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(Costos)
        self.label_27.setGeometry(QtCore.QRect(780, 160, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(Costos)
        self.label_28.setGeometry(QtCore.QRect(780, 200, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(Costos)
        self.label_29.setGeometry(QtCore.QRect(780, 120, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(Costos)
        self.label_30.setGeometry(QtCore.QRect(780, 240, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(Costos)
        self.label_31.setGeometry(QtCore.QRect(780, 290, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.line = QtWidgets.QFrame(Costos)
        self.line.setGeometry(QtCore.QRect(1010, 70, 20, 401))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Costos)
        self.line_2.setGeometry(QtCore.QRect(760, 330, 431, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Costos)
        self.line_3.setGeometry(QtCore.QRect(753, 70, 20, 401))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(Costos)
        self.line_4.setGeometry(QtCore.QRect(1183, 70, 20, 401))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(Costos)
        self.line_5.setGeometry(QtCore.QRect(760, 120, 431, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(Costos)
        self.line_6.setGeometry(QtCore.QRect(760, 160, 431, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(Costos)
        self.line_7.setGeometry(QtCore.QRect(760, 240, 431, 16))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(Costos)
        self.line_8.setGeometry(QtCore.QRect(760, 200, 431, 16))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(Costos)
        self.line_9.setGeometry(QtCore.QRect(760, 280, 431, 16))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.label_38 = QtWidgets.QLabel(Costos)
        self.label_38.setGeometry(QtCore.QRect(780, 340, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(Costos)
        self.label_39.setGeometry(QtCore.QRect(780, 380, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(Costos)
        self.label_40.setGeometry(QtCore.QRect(780, 420, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.line_10 = QtWidgets.QFrame(Costos)
        self.line_10.setGeometry(QtCore.QRect(760, 460, 431, 20))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(Costos)
        self.line_11.setGeometry(QtCore.QRect(760, 370, 431, 20))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(Costos)
        self.line_12.setGeometry(QtCore.QRect(760, 410, 431, 20))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.label_44 = QtWidgets.QLabel(Costos)
        self.label_44.setGeometry(QtCore.QRect(760, 490, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setStyleSheet("background-color: rgb(73, 255, 70);")
        self.label_44.setObjectName("label_44")
        self.label_Costo_Total = QtWidgets.QLabel(Costos)
        self.label_Costo_Total.setGeometry(QtCore.QRect(1020, 490, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_Costo_Total.setFont(font)
        self.label_Costo_Total.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_Costo_Total.setAutoFillBackground(False)
        self.label_Costo_Total.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_Costo_Total.setText("")
        self.label_Costo_Total.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Costo_Total.setObjectName("label_Costo_Total")
        self.label_costo_carcaza = QtWidgets.QLabel(Costos)
        self.label_costo_carcaza.setGeometry(QtCore.QRect(1020, 70, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_costo_carcaza.setFont(font)
        self.label_costo_carcaza.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_costo_carcaza.setAutoFillBackground(False)
        self.label_costo_carcaza.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_costo_carcaza.setText("")
        self.label_costo_carcaza.setAlignment(QtCore.Qt.AlignCenter)
        self.label_costo_carcaza.setObjectName("label_costo_carcaza")
        self.label_costo_platos = QtWidgets.QLabel(Costos)
        self.label_costo_platos.setGeometry(QtCore.QRect(1020, 130, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_costo_platos.setFont(font)
        self.label_costo_platos.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_costo_platos.setAutoFillBackground(False)
        self.label_costo_platos.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_costo_platos.setText("")
        self.label_costo_platos.setAlignment(QtCore.Qt.AlignCenter)
        self.label_costo_platos.setObjectName("label_costo_platos")
        self.label_costo_condensador = QtWidgets.QLabel(Costos)
        self.label_costo_condensador.setGeometry(QtCore.QRect(1020, 170, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_costo_condensador.setFont(font)
        self.label_costo_condensador.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_costo_condensador.setAutoFillBackground(False)
        self.label_costo_condensador.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_costo_condensador.setText("")
        self.label_costo_condensador.setAlignment(QtCore.Qt.AlignCenter)
        self.label_costo_condensador.setObjectName("label_costo_condensador")
        self.label_costo_reboiler = QtWidgets.QLabel(Costos)
        self.label_costo_reboiler.setGeometry(QtCore.QRect(1020, 210, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_costo_reboiler.setFont(font)
        self.label_costo_reboiler.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_costo_reboiler.setAutoFillBackground(False)
        self.label_costo_reboiler.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_costo_reboiler.setText("")
        self.label_costo_reboiler.setAlignment(QtCore.Qt.AlignCenter)
        self.label_costo_reboiler.setObjectName("label_costo_reboiler")
        self.label_Costo_Equipos = QtWidgets.QLabel(Costos)
        self.label_Costo_Equipos.setGeometry(QtCore.QRect(1020, 250, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_Costo_Equipos.setFont(font)
        self.label_Costo_Equipos.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_Costo_Equipos.setAutoFillBackground(False)
        self.label_Costo_Equipos.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_Costo_Equipos.setText("")
        self.label_Costo_Equipos.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Costo_Equipos.setObjectName("label_Costo_Equipos")
        self.label_Costo_Equipos_Anual = QtWidgets.QLabel(Costos)
        self.label_Costo_Equipos_Anual.setGeometry(QtCore.QRect(1020, 290, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_Costo_Equipos_Anual.setFont(font)
        self.label_Costo_Equipos_Anual.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_Costo_Equipos_Anual.setAutoFillBackground(False)
        self.label_Costo_Equipos_Anual.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_Costo_Equipos_Anual.setText("")
        self.label_Costo_Equipos_Anual.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Costo_Equipos_Anual.setObjectName("label_Costo_Equipos_Anual")
        self.label_costo_enfriamiento = QtWidgets.QLabel(Costos)
        self.label_costo_enfriamiento.setGeometry(QtCore.QRect(1020, 340, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_costo_enfriamiento.setFont(font)
        self.label_costo_enfriamiento.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_costo_enfriamiento.setAutoFillBackground(False)
        self.label_costo_enfriamiento.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_costo_enfriamiento.setText("")
        self.label_costo_enfriamiento.setAlignment(QtCore.Qt.AlignCenter)
        self.label_costo_enfriamiento.setObjectName("label_costo_enfriamiento")
        self.label_costo_calentamiento = QtWidgets.QLabel(Costos)
        self.label_costo_calentamiento.setGeometry(QtCore.QRect(1020, 380, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_costo_calentamiento.setFont(font)
        self.label_costo_calentamiento.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_costo_calentamiento.setAutoFillBackground(False)
        self.label_costo_calentamiento.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_costo_calentamiento.setText("")
        self.label_costo_calentamiento.setAlignment(QtCore.Qt.AlignCenter)
        self.label_costo_calentamiento.setObjectName("label_costo_calentamiento")
        self.label_Costo_Servicios = QtWidgets.QLabel(Costos)
        self.label_Costo_Servicios.setGeometry(QtCore.QRect(1020, 420, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_Costo_Servicios.setFont(font)
        self.label_Costo_Servicios.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_Costo_Servicios.setAutoFillBackground(False)
        self.label_Costo_Servicios.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_Costo_Servicios.setText("")
        self.label_Costo_Servicios.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Costo_Servicios.setObjectName("label_Costo_Servicios")
        self.label_32 = QtWidgets.QLabel(Costos)
        self.label_32.setGeometry(QtCore.QRect(490, 250, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(Costos)
        self.label_33.setGeometry(QtCore.QRect(480, 650, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(Costos)
        self.label_34.setGeometry(QtCore.QRect(730, 830, 421, 16))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(Costos)
        self.label_35.setGeometry(QtCore.QRect(70, 450, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(Costos)
        self.label_36.setGeometry(QtCore.QRect(480, 700, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(Costos)
        self.label_37.setGeometry(QtCore.QRect(480, 330, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.line_13 = QtWidgets.QFrame(Costos)
        self.line_13.setGeometry(QtCore.QRect(360, 20, 311, 20))
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.line_14 = QtWidgets.QFrame(Costos)
        self.line_14.setGeometry(QtCore.QRect(360, 140, 311, 20))
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.line_15 = QtWidgets.QFrame(Costos)
        self.line_15.setGeometry(QtCore.QRect(353, 30, 20, 121))
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.line_16 = QtWidgets.QFrame(Costos)
        self.line_16.setGeometry(QtCore.QRect(660, 30, 20, 121))
        self.line_16.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.txt_year = QtWidgets.QLineEdit(Costos)
        self.txt_year.setGeometry(QtCore.QRect(70, 70, 113, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txt_year.setFont(font)
        self.txt_year.setObjectName("txt_year")
        self.txt_tiempo = QtWidgets.QLineEdit(Costos)
        self.txt_tiempo.setGeometry(QtCore.QRect(250, 110, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txt_tiempo.setFont(font)
        self.txt_tiempo.setObjectName("txt_tiempo")
        self.txt_agua = QtWidgets.QLineEdit(Costos)
        self.txt_agua.setGeometry(QtCore.QRect(550, 70, 113, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txt_agua.setFont(font)
        self.txt_agua.setObjectName("txt_agua")
        self.txt_vapor = QtWidgets.QLineEdit(Costos)
        self.txt_vapor.setGeometry(QtCore.QRect(550, 110, 113, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txt_vapor.setFont(font)
        self.txt_vapor.setObjectName("txt_vapor")
        self.txt_presion = QtWidgets.QLineEdit(Costos)
        self.txt_presion.setGeometry(QtCore.QRect(130, 210, 113, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txt_presion.setFont(font)
        self.txt_presion.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.txt_presion.setObjectName("txt_presion")
        self.txt_material = QtWidgets.QLineEdit(Costos)
        self.txt_material.setGeometry(QtCore.QRect(150, 260, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txt_material.setFont(font)
        self.txt_material.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.txt_material.setObjectName("txt_material")
        self.txt_qreboiler = QtWidgets.QLineEdit(Costos)
        self.txt_qreboiler.setGeometry(QtCore.QRect(580, 200, 113, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txt_qreboiler.setFont(font)
        self.txt_qreboiler.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.txt_qreboiler.setObjectName("txt_qreboiler")
        self.txt_cp = QtWidgets.QLineEdit(Costos)
        self.txt_cp.setGeometry(QtCore.QRect(590, 250, 113, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txt_cp.setFont(font)
        self.txt_cp.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.txt_cp.setObjectName("txt_cp")
        self.txt_t2 = QtWidgets.QLineEdit(Costos)
        self.txt_t2.setGeometry(QtCore.QRect(610, 290, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txt_t2.setFont(font)
        self.txt_t2.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.txt_t2.setObjectName("txt_t2")
        self.txt_T1 = QtWidgets.QLineEdit(Costos)
        self.txt_T1.setGeometry(QtCore.QRect(350, 240, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txt_T1.setFont(font)
        self.txt_T1.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.txt_T1.setObjectName("txt_T1")
        self.txt_t1 = QtWidgets.QLineEdit(Costos)
        self.txt_t1.setGeometry(QtCore.QRect(300, 280, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txt_t1.setFont(font)
        self.txt_t1.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.txt_t1.setObjectName("txt_t1")
        self.txt_T2 = QtWidgets.QLineEdit(Costos)
        self.txt_T2.setGeometry(QtCore.QRect(360, 320, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txt_T2.setFont(font)
        self.txt_T2.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.txt_T2.setObjectName("txt_T2")
        self.txt_platos = QtWidgets.QLineEdit(Costos)
        self.txt_platos.setGeometry(QtCore.QRect(480, 430, 113, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txt_platos.setFont(font)
        self.txt_platos.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.txt_platos.setObjectName("txt_platos")
        self.txt_espacio = QtWidgets.QLineEdit(Costos)
        self.txt_espacio.setGeometry(QtCore.QRect(480, 470, 113, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txt_espacio.setFont(font)
        self.txt_espacio.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.txt_espacio.setObjectName("txt_espacio")
        self.txt_diametro = QtWidgets.QLineEdit(Costos)
        self.txt_diametro.setGeometry(QtCore.QRect(480, 520, 113, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txt_diametro.setFont(font)
        self.txt_diametro.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.txt_diametro.setObjectName("txt_diametro")
        self.txt_tempfondo = QtWidgets.QLineEdit(Costos)
        self.txt_tempfondo.setGeometry(QtCore.QRect(490, 750, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txt_tempfondo.setFont(font)
        self.txt_tempfondo.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.txt_tempfondo.setObjectName("txt_tempfondo")
        self.txt_qcondensador = QtWidgets.QLineEdit(Costos)
        self.txt_qcondensador.setGeometry(QtCore.QRect(592, 600, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txt_qcondensador.setFont(font)
        self.txt_qcondensador.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.txt_qcondensador.setObjectName("txt_qcondensador")
        self.txt_qvap = QtWidgets.QLineEdit(Costos)
        self.txt_qvap.setGeometry(QtCore.QRect(590, 650, 113, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txt_qvap.setFont(font)
        self.txt_qvap.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.txt_qvap.setObjectName("txt_qvap")
        self.txt_tsat = QtWidgets.QLineEdit(Costos)
        self.txt_tsat.setGeometry(QtCore.QRect(270, 680, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txt_tsat.setFont(font)
        self.txt_tsat.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.txt_tsat.setObjectName("txt_tsat")
        self.label_41 = QtWidgets.QLabel(Costos)
        self.label_41.setGeometry(QtCore.QRect(330, 380, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(Costos)
        self.label_42.setGeometry(QtCore.QRect(230, 760, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.txt_U1 = QtWidgets.QLineEdit(Costos)
        self.txt_U1.setGeometry(QtCore.QRect(430, 370, 113, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txt_U1.setFont(font)
        self.txt_U1.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.txt_U1.setObjectName("txt_U1")
        self.txt_U2 = QtWidgets.QLineEdit(Costos)
        self.txt_U2.setGeometry(QtCore.QRect(330, 750, 113, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txt_U2.setFont(font)
        self.txt_U2.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.txt_U2.setObjectName("txt_U2")
        self.label.raise_()
        self.label_2.raise_()
        self.btn_calcular.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.label_24.raise_()
        self.label_25.raise_()
        self.label_26.raise_()
        self.label_27.raise_()
        self.label_28.raise_()
        self.label_29.raise_()
        self.label_30.raise_()
        self.label_31.raise_()
        self.line.raise_()
        self.line_3.raise_()
        self.line_4.raise_()
        self.label_38.raise_()
        self.label_39.raise_()
        self.label_40.raise_()
        self.label_44.raise_()
        self.label_Costo_Total.raise_()
        self.label_costo_carcaza.raise_()
        self.label_costo_platos.raise_()
        self.label_costo_condensador.raise_()
        self.label_costo_reboiler.raise_()
        self.label_Costo_Equipos.raise_()
        self.label_Costo_Equipos_Anual.raise_()
        self.label_costo_enfriamiento.raise_()
        self.label_costo_calentamiento.raise_()
        self.label_Costo_Servicios.raise_()
        self.label_32.raise_()
        self.label_33.raise_()
        self.label_34.raise_()
        self.label_35.raise_()
        self.label_36.raise_()
        self.label_37.raise_()
        self.line_13.raise_()
        self.line_14.raise_()
        self.line_15.raise_()
        self.line_16.raise_()
        self.line_8.raise_()
        self.line_5.raise_()
        self.line_6.raise_()
        self.line_7.raise_()
        self.line_9.raise_()
        self.line_2.raise_()
        self.line_11.raise_()
        self.line_10.raise_()
        self.line_12.raise_()
        self.txt_year.raise_()
        self.txt_tiempo.raise_()
        self.txt_agua.raise_()
        self.txt_vapor.raise_()
        self.txt_presion.raise_()
        self.txt_material.raise_()
        self.txt_qreboiler.raise_()
        self.txt_cp.raise_()
        self.txt_t2.raise_()
        self.txt_T1.raise_()
        self.txt_t1.raise_()
        self.txt_T2.raise_()
        self.txt_platos.raise_()
        self.txt_espacio.raise_()
        self.txt_diametro.raise_()
        self.txt_tempfondo.raise_()
        self.txt_qcondensador.raise_()
        self.txt_qvap.raise_()
        self.txt_tsat.raise_()
        self.label_41.raise_()
        self.label_42.raise_()
        self.txt_U1.raise_()
        self.txt_U2.raise_()

        self.retranslateUi(Costos)
        QtCore.QMetaObject.connectSlotsByName(Costos)

    def retranslateUi(self, Costos):
        _translate = QtCore.QCoreApplication.translate
        Costos.setWindowTitle(_translate("Costos", "Costo de columna"))
        self.btn_calcular.setText(_translate("Costos", "CALCULAR"))
        self.label_3.setText(_translate("Costos", "AÑO:"))
        self.label_4.setText(_translate("Costos", "Número de platos:"))
        self.label_5.setText(_translate("Costos", "Espacio entre platos [ft]:"))
        self.label_6.setText(_translate("Costos", "Diámetro [ft]:"))
        self.label_7.setText(_translate("Costos", "Presión [bar]:"))
        self.label_8.setText(_translate("Costos", "Material [CS/SS]:"))
        self.label_9.setText(_translate("Costos", "Condensador"))
        self.label_10.setText(_translate("Costos", "Reboiler"))
        self.label_11.setText(_translate("Costos", "Q [kW]="))
        self.label_12.setText(_translate("Costos", "TIEMPO DE INVERSIÓN [AÑOS]:"))
        self.label_13.setText(_translate("Costos", "Q [kW]="))
        self.label_14.setText(_translate("Costos", "Costo de servicios ($/1000 kg)"))
        self.label_15.setText(_translate("Costos", "Agua de enfriamiento"))
        self.label_16.setText(_translate("Costos", "Vapor de calentamiento"))
        self.label_17.setText(_translate("Costos", "T1="))
        self.label_18.setText(_translate("Costos", "Tsatv"))
        self.label_19.setText(_translate("Costos", "T2="))
        self.label_20.setText(_translate("Costos", "t1="))
        self.label_22.setText(_translate("Costos", "t2="))
        self.label_23.setText(_translate("Costos", "t="))
        self.label_24.setText(_translate("Costos", "MÉTODO DE GUTHRIE"))
        self.label_25.setText(_translate("Costos", "                       RESULTADOS"))
        self.label_26.setText(_translate("Costos", "Costo de columna"))
        self.label_27.setText(_translate("Costos", "Costo condensador"))
        self.label_28.setText(_translate("Costos", "Costo reboiler"))
        self.label_29.setText(_translate("Costos", "Costo platos"))
        self.label_30.setText(_translate("Costos", "Costo de equipos"))
        self.label_31.setText(_translate("Costos", "Costo de equipos [$/AÑO]"))
        self.label_38.setText(_translate("Costos", "Costo enfriamiento [$/AÑO]"))
        self.label_39.setText(_translate("Costos", "Costo calentamiento [$/AÑO]"))
        self.label_40.setText(_translate("Costos", "Costo servicios [$/AÑO]"))
        self.label_44.setText(_translate("Costos", "  COSTO TOTAL [$/AÑO]"))
        self.label_32.setText(_translate("Costos", "CP [kJ/kg°C]="))
        self.label_33.setText(_translate("Costos", "Qvap [kJ/kg]="))
        self.label_34.setText(_translate("Costos", "Realizado por Abraham Rodarte de la Fuente el 1 de diciembre del 2020"))
        self.label_35.setText(_translate("Costos", "ALIMENTACIÓN"))
        self.label_36.setText(_translate("Costos", "FONDO"))
        self.label_37.setText(_translate("Costos", "DESTILADO"))
        self.label_41.setText(_translate("Costos", "U1 [W/m2°C]="))
        self.label_42.setText(_translate("Costos", "U2 [W/m2°C]="))
import imagenes_rc

class CostoColumna(QDialog):
    def __init__(self):
        super().__init__()

        self.ui = Ui_Costos()
        self.ui.setupUi(self)

        self.ui.btn_calcular.clicked.connect(self.calcular)
        self.show()
    def calcular(self):
        #Captura de la pantalla pantalla
        ahora=datetime.now()
        segundo=ahora.second
        minuto= ahora.minute
        segundo= segundo/100
        hora= minuto+segundo
        nombre=str("Captura-"+str(hora)+".png")
        screen = mss.mss()
        screen.shot(output="Capturas/"+nombre)


        Tabla_años=[1957,1958,1959,1966,1968,1970,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020]
        Tabla_indices= [100,100,100,107.2,113.7,125.7,182.4,192.1,204.1,218.8,238.1,261.2,297,314,316.9,322.7,325.3,318.4,323.8,342.5,355.4,357.6,361.3,358.2,359.2,368.1,381.1,381.7,386.5,389.5,390.6,394.1,394.3,395.6,402,444.2,468.2,499.6,525.4,549.2,521.9,550.8,585.7,584.6,567.3,576.1,580,584.9,590.3,594.4,599.1,579.1]
        AÑO=0
        P=0
        MATERIAL=0
        D=0
        N=0
        L=0
        PCond=0  
        QCond= 0
        Tem_Cond=0 
        PReb=0   
        QReb= 0
        Tem_Reb=0
        Espacio=0
        indice=0   
        #Indice
        if len(self.ui.txt_year.text())>0:
            AÑO=float(self.ui.txt_year.text())
        i=0
        for year in Tabla_años:
            if year == AÑO:
                indice = Tabla_indices[i]
            i=i+1
        #costocolumna
        if len(self.ui.txt_presion.text())>0:
            P=float(self.ui.txt_presion.text())
        if len(self.ui.txt_material.text())>0:
            MATERIAL=str(self.ui.txt_material.text())
        if len(self.ui.txt_diametro.text())>0:
            D=float(self.ui.txt_diametro.text())
        if len(self.ui.txt_espacio.text())>0:
            Espacio=float(self.ui.txt_espacio.text())
        if len(self.ui.txt_platos.text())>0:
            N=float(self.ui.txt_platos.text())
        L=Espacio*N
        C0 = 1000
        L0 = 4.0
        D0 = 3.0
        ALFA = 0.81
        BETA = 1.05
        Fp = ((((P-1)*D*(1/3.28084))/(2*(850-0.6*(P-1))))+0.00315)/0.0063
        if Fp<1:
            Fp = 1
        if MATERIAL=='SS':
            FM=3.1
        else:
            FM=1 
        B1=2.25
        B2=1.82
        C = C0*((L/L0)**ALFA)*((D/D0))**BETA
        Fd=B1+(B2*FM*Fp)
        if C<200000:
            FACTOR=4.23
        elif C<400000:
            FACTOR=4.12
        elif C<600000:
            FACTOR=4.07
        elif C<800000:
            FACTOR=4.06
        else:
            FACTOR=4.02
        CFOB =C*(Fd+Fp)*(FM)*(indice/113.7)
        CMD = C*FACTOR
        CMDA_Columna= CMD +(CFOB-C)
        str_Columna="${:,.2f}".format(CMDA_Columna)
        #Costo platos
        C0 = 180
        L0 = 10.0
        D0 = 2.0
        ALFA = 0.97
        BETA = 1.45
        if N <20:
            Fq=10**(0.4771+0.08516*math.log10(N)-0.3473*(math.log10(N)**2))
                

        else:
            Fq=1
        Fp = 1

        C = C0*((L/L0)**ALFA)*((D/D0))**BETA
        if MATERIAL=='SS':
            FM =1.7
            FBM=1.9
            Fd=FBM*float(Fq)
            FACTOR=1

        else:
            FM =1.7
            FBM=1
            Fd=FBM*float(Fq)
            FACTOR = 1
        CFOB =C*(Fd+Fp)*(FM)*(indice/113.7)
        CMD = C*FACTOR
        CMDA_Platos= CMD +(CFOB-C)
        str_Platos="${:,.2f}".format(CMDA_Platos)
        #Calculo Condensador
        PCon=P-0.7
        T1=0
        t1=0
        t2=0
        U1=0
        FACTOR_cond=0
        #Aqui me equivoque jajaja puse alreves las etiquetas de los calores para el reboiler y el condensador
        if len(self.ui.txt_qreboiler.text())>0:
            QCond=float(self.ui.txt_qreboiler.text())
        if len(self.ui.txt_T2.text())>0:
            Tem_Cond=float(self.ui.txt_T2.text())
        if len(self.ui.txt_T1.text())>0:
            T1=float(self.ui.txt_T1.text())
        if len(self.ui.txt_t1.text())>0:
            t1=float(self.ui.txt_t1.text())
        if len(self.ui.txt_t2.text())>0:
            t2=float(self.ui.txt_t2.text())
        if len(self.ui.txt_U1.text())>0:
            U1=float(self.ui.txt_U1.text())
        deltaT_cond=((Tem_Cond-t1)-(T1-t2))/(math.log((Tem_Cond-t1)/(T1-t2)))
        S=(QCond/(U1*deltaT_cond))*((3.28084/1)**2)*1000
        if S <100:
            C_cond=300*((S/5.5)**0.024)
            FACTOR_cond=1.83
        else:
            C_cond=5000*((S/400)**0.65)
            if C_cond<200000:
                FACTOR_cond=3.29
            elif C_cond<400000:
                FACTOR_cond=3.18
            elif C_cond<600000:
                FACTOR_cond=3.14
            elif C_cond<800000:
                FACTOR_cond=3.12
            else:
                FACTOR_cond=3.09 
        if PCon<6:
            C1=0
            C2=0
            C3=0
        else:
            C1=0.03881
            C2=-0.11272
            C3=0.08183

        if PCon<6:
            Fp=1
        elif PCon==6:
            Fp=1
        else:
            logFp=C1+C2*math.log10(PCon-1)+C3*math.log10(PCon-1)**2
            Fp= 10**(logFp)
        if Fp<1:
            Fp=1
        if MATERIAL=='SS':
            FM=1.8
        else:
            FM=1
        B1=1.63
        B2=1.66
        Fd=(B1+B2*FM*Fp)
        CFOB =C_cond*(Fd+Fp)*(FM)*(indice/113.7)
        CMD = C_cond*FACTOR_cond
        CMDA_Condensador= CMD +(CFOB-C_cond)
        str_Condensador="${:,.2f}".format(CMDA_Condensador)
        #Calculo reboiler
        Tsat=0
        Tem_Reb=0
        QReb=0
        Qvap=0
        U2=0
        FACTOR_reb=0
        if len(self.ui.txt_tempfondo.text())>0:
            Tem_Reb=float(self.ui.txt_tempfondo.text())
        if len(self.ui.txt_tsat.text())>0:
            Tsat=float(self.ui.txt_tsat.text())
        #Aqui me equivoque jajaja puse alreves las etiquetas de los calores para el reboiler y el condensador, parte 2 xD
        if len(self.ui.txt_qcondensador.text())>0:
            QReb=float(self.ui.txt_qcondensador.text())
        if len(self.ui.txt_qvap.text())>0:
            Qvap=float(self.ui.txt_qvap.text())
        if len(self.ui.txt_U2.text())>0:
            U2=float(self.ui.txt_U2.text())
        deltaT=Tsat-Tem_Reb
        S=(QReb/(U2*deltaT))*((3.28084/1)**2)*1000
        if S<100:
            C_reb=300*((S/5.5)**0.024)
            FACTOR_reb=1.83
        else:
            C_reb=5000*((S/400)**0.65)
            if C_reb<200000:
                FACTOR_reb=3.29
            elif C_reb<400000:
                FACTOR_reb=3.18
            elif C_reb<600000:
                FACTOR_reb=3.14
            elif C_reb<800000:
                FACTOR_reb=3.12
            else:
                FACTOR_reb=3.09 
        if P<6:
            C1=0
            C2=0
            C3=0
        else:
            C1=0.03881
            C2=-0.11272
            C3=0.08183
    
        if P<6:
            Fp=1
        elif P==6:
            Fp=1
        else:
            logFp=C1+C2*math.log10(P-1)+C3*math.log10(P-1)**2
            Fp= 10**(logFp)
        if Fp<1:
            Fp=1
        if MATERIAL=='SS':
            FM=1.8
        else:
            FM=1
        B1=1.63
        B2=1.66
        Fd=(B1+B2*FM*Fp)
        CFOB =C_reb*(Fd+Fp)*(FM)*(indice/113.7)
        CMD = C_reb*FACTOR_reb
        CMDA_Reboiler= CMD +(CFOB-C_reb)
        str_Reboiler="${:,.2f}".format(CMDA_Reboiler)
        #Suma de costo de equipos
        CostoEquipos= CMDA_Columna+CMDA_Platos+CMDA_Condensador+CMDA_Reboiler
        strCostoEquipos="${:,.2f}".format(CostoEquipos)
        #Costo anual de equipos
        TI=0
        if len(self.ui.txt_tiempo.text())>0:
            TI=float(self.ui.txt_tiempo.text())
        CostoEquipoAnual=CostoEquipos/TI
        strCostoEquiposAnual="{:,.2f}".format(CostoEquipoAnual)
        #Costo agua de enfriamiento
        CP=0
        tem_agua=t2-t1
        costoa_1000kg=0
        if len(self.ui.txt_cp.text())>0:
            CP=float(self.ui.txt_cp.text())
        if len(self.ui.txt_agua.text())>0:
            costoa_1000kg=float(self.ui.txt_agua.text())
        Flujo_Anual=(QCond/(CP*tem_agua))*(60*60*24*337.5)
        CostoAgua_Anual=Flujo_Anual*costoa_1000kg/1000
        strCostoAgua="{:,.2f}".format(CostoAgua_Anual)
        #Costo vapor de calentamiento
        costo_vapor_1000kg=0
        if len(self.ui.txt_vapor.text())>0:
            costo_vapor_1000kg=float(self.ui.txt_vapor.text())
        Flujo_Anual_Vapor= (QReb/Qvap)*(60*60*24*337.5)
        Costo_Vapor_Anual=Flujo_Anual_Vapor*costo_vapor_1000kg/1000
        strCostoVapor="{:,.2f}".format(Costo_Vapor_Anual)
        #Costo Servicios
        Costo_Servicios_Anual=Costo_Vapor_Anual+CostoAgua_Anual
        strCostoServicios="{:,.2f}".format(Costo_Servicios_Anual)
        #Costo Total
        Costo_Total=Costo_Servicios_Anual+CostoEquipoAnual
        strCostoTotal="{:,.2f}".format(Costo_Total)
        #Impresión de resultados
        self.ui.label_costo_carcaza.setText(str_Columna)
        self.ui.label_costo_platos.setText(str_Platos)
        self.ui.label_costo_condensador.setText(str_Condensador)
        self.ui.label_costo_reboiler.setText(str_Reboiler)
        self.ui.label_Costo_Equipos.setText(strCostoEquipos)
        self.ui.label_Costo_Equipos_Anual.setText(strCostoEquiposAnual)
        self.ui.label_costo_enfriamiento.setText(strCostoAgua)
        self.ui.label_costo_calentamiento.setText(strCostoVapor)
        self.ui.label_Costo_Servicios.setText(strCostoServicios)
        self.ui.label_Costo_Total.setText(strCostoTotal)
        

if __name__ == '__main__':
    app = QApplication(sys.argv)
    dialog = CostoColumna()
    dialog.show()

    sys.exit(app.exec_())